# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f97e94d29bc3e5ad56f433357073ca5b7e30a334fd21cd3e0265e780f8462fc201c0b98ee843db68fde0685fcefefb9704d14f5dd9ba8f0a34756b6e6921463d

test:
  secret_key_base: f26e909758311075cc787ec5154db1f710e49302b93b84377e973a460829809a05d013706c985471d35c9e5b9f2b72127cb381afffefb198e1bfd5387bb37d1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
